# Frontend Pipeline Stages
stages:
  - acquire-backend
  - deploy

variables:
  PATH_SOURCE_BACKEND: "C:\\Program Files\\Backend Project Integration 4"
  PATH_DEPLOY_FRONTEND: "C:\\Program Files\\Project Integration 4"
  
default:
  tags:
    - windows
  before_script:
    - $ErrorActionPreference = "Stop"

acquire-backend-job:
  stage: acquire-backend
  script:
    - echo "Adquirindo artefatos compartilhados da pasta fixa..."
    - New-Item -Path "$CI_PROJECT_DIR\build\backend\Release" -ItemType Directory -Force
    - New-Item -Path "$CI_PROJECT_DIR\build\frontend\Release" -ItemType Directory -Force

    - Copy-Item -Path "$env:PATH_SOURCE_BACKEND\Projeto GRPC.exe" -Destination "$CI_PROJECT_DIR\build\backend\Release\" -Force
    - Copy-Item -Path "$env:PATH_SOURCE_BACKEND\Projeto GRPC_lib.lib" -Destination "$CI_PROJECT_DIR/build\backend\Release\" -Force
    - Copy-Item -Path "$env:PATH_SOURCE_BACKEND\Display.exe" -Destination "$CI_PROJECT_DIR\build\frontend\Release\" -Force
    - Copy-Item -Path "$env:PATH_SOURCE_BACKEND\Display_lib.lib" -Destination "$CI_PROJECT_DIR\build\frontend\Release\" -Force
  artifacts:
    name: "backend-artifacts-$CI_COMMIT_REF_SLUG"
    paths:
      - build/backend/Release/Projeto GRPC
      - build/backend/Release/Projeto GRPC_lib.lib
      - build/frontend/Release/Display.exe
      - build/frontend/Release/Display_lib.lib
    expire_in: 2 days

deploy-job:
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  dependencies:
    - acquire-backend-job
  script:
    - echo "Criando pacote auto-extraível (.exe)..."
    - & "C:\Program Files\7-Zip\7z.exe" a -sfx Projeto_Completo.exe .\build\backend\Release\Projeto GRPC .\build\frontend\Release\Display.exe
  artifacts:
    name: "Release-Package-$CI_COMMIT_SHORT_SHA"
    paths:
      - ./Projeto_Completo.exe
    expire_in: 5 days