# Frontend Pipeline Stages
stages:
  # - Lint
  # - new deploy

# Pegar o executável do back da pasta fixa do computador
# Lint Job no código do front

# New Deploy Job: disponibilizar o executável do front como artefato, ou seja, o executável do front vai ser gerado e disponibilizado para download no Gitlab 
